# Generated by Django 6.0 on 2026-02-06 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-created_at'], 'verbose_name': 'Обратная связь', 'verbose_name_plural': 'Обратная связь'},
        ),
        migrations.AddField(
            model_name='feedback',
            name='subject',
            field=models.CharField(choices=[('thanks', 'Благодарность'), ('complaint', 'Жалоба'), ('other', 'Другое')], default='other', max_length=100, verbose_name='Тема обращения'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя отправителя'),
        ),
    ]
