name: lint and test

on:
  push:
    branches-ignore:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v6

      - name: setup uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: 3.14
          enable-cache: true

      - name: install dependencies
        run: uv sync --frozen

      - name: run linters
        run: uv run pre-commit run --all-files

  test:
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.12", "3.13", "3.14" ]
    services:
      redis:
        image: redis:alpine
        ports:
          - 6379:6379
    steps:
      - name: checkout code
        uses: actions/checkout@v6

      - name: setup uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true

      - name: install dependencies
        run: uv sync --frozen

      - name: create.env
        run: cp .env.example .env

      - name: run tests
        run: |
          cd src/django_project
          uv run manage.py test --verbosity=2

      - name: Run Actions Telegram Notify
        uses: proDreams/actions-telegram-notifier@main
        if: always()
        with:
          token: ${{ secrets.TELEGRAM_TOKEN }}
          chat_id: ${{ secrets.TELEGRAM_CHAT_ID }}
          status: ${{ job.status }}
          notify_fields: "actor,repository,workflow"
